### ISSUE TITLE
Scale out error when executing some special application:　Cannot find matched InputGateDeploymentDescriptor

### ISSUE THREAD

**Issue by maxCodeVector** [sane-lab/flink#58]
It will throw an exception when scale-out some special application: `Cannot find matched InputGateDeploymentDescriptor`

Branch: rescale-1.10
Environment: ubuntu 18.04, standalone cluster mode (both multiple machine and single machine)

The operator graph of error application:
sourc (p=1)  -> map (p=2)  -> filter (p=2) -> sink (p=1) 

When scale map operator from parallelism 2 to 3, it will throw such exception:
```
2020-10-21 19:44:36,395 INFO  org.apache.flink.streaming.runtime.tasks.StreamTask           - ++++++ error
java.lang.IllegalStateException: Cannot find matched InputGateDeploymentDescriptor
	at org.apache.flink.runtime.rescale.TaskRescaleManager$TaskRescaleMeta.getMatchedInputGateDescriptor(TaskRescaleManager.java:322)
	at org.apache.flink.runtime.rescale.TaskRescaleManager.substituteInputGateChannels(TaskRescaleManager.java:192)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.initReconnect(StreamTask.java:1090)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.checkRescalePoint(StreamTask.java:1137)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$performCheckpoint$5(StreamTask.java:890)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:94)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.performCheckpoint(StreamTask.java:860)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointOnBarrier(StreamTask.java:820)
	at org.apache.flink.streaming.runtime.io.CheckpointBarrierHandler.notifyCheckpoint(CheckpointBarrierHandler.java:86)
	at org.apache.flink.streaming.runtime.io.CheckpointBarrierAligner.processBarrier(CheckpointBarrierAligner.java:113)
	at org.apache.flink.streaming.runtime.io.CheckpointedInputGate.pollNext(CheckpointedInputGate.java:155)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.emitNext(StreamTaskNetworkInput.java:140)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:74)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:323)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:187)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:498)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:482)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:733)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:556)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by maxCodeVector** [comment]
When two operators have partition type: `FORWARD`,　scale-out the former operator will cause such exception. In the above example, the partition type of map and filter is `FORWARD`.
